{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zaehl-o-mat.fullname" . }}-postgresql
  labels:
    {{- include "zaehl-o-mat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zaehl-o-mat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "zaehl-o-mat.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - port: tcp-postgresql
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zaehl-o-mat.fullname" . }}-backend
  labels:
    {{- include "zaehl-o-mat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zaehl-o-mat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressFrom.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressFrom.podSelector | nindent 12 }}
      ports:
        - port: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zaehl-o-mat.fullname" . }}-frontend
  labels:
    {{- include "zaehl-o-mat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zaehl-o-mat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressFrom.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressFrom.podSelector | nindent 12 }}
      ports:
        - port: http
          protocol: TCP
{{- end }}
